// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "DriveTrain.h"
#include "../RobotMap.h"
#include "../Commands/DriveWithJoysticks.h"

DriveTrain::DriveTrain() : Subsystem("DriveTrain") {
    cANJaguarLeft = RobotMap::driveTrainCANTalonLeft;
    cANJaguarRight = RobotMap::driveTrainCANTalonRight;
    robotDrive21 = RobotMap::driveTrainRobotDrive21;
}

void DriveTrain::InitDefaultCommand() {
        SetDefaultCommand(new DriveWithJoysticks());
}

void DriveTrain::setdrive(float speedleft, float speedright){
	robotDrive21.get()->TankDrive(speedleft, speedright);
}

void DriveTrain::openmotors(){
	cANJaguarRight.get()->SetControlMode(CANSpeedController::kPercentVbus);
	cANJaguarRight.get()->EnableControl();
	cANJaguarRight.get()->Set(0.0f);

	cANJaguarLeft.get()->SetControlMode(CANSpeedController::kPercentVbus);
	cANJaguarLeft.get()->EnableControl();
	cANJaguarLeft.get()->Set(0.0f);
}

