// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
#define CheckDigitalInputChannel(n) (switchValues & (1 << n)) //where n is the channel

#include "AutonomousCommand.h"

AutonomousCommand::AutonomousCommand(): Command() {
	Requires(Robot::driveTrain.get());
	Requires(Robot::lifter.get());

}

void AutonomousCommand::Initialize() {

}

void AutonomousCommand::Execute() {
	switch(visionStatus){
	case 0: //Nothing seen
		break;
	case 1: //tower

		break;
	case 2: //lowbar
		break;
	default:
		printf("I DON'T KNOW WHAT i SEE!!!");
	}
}

bool AutonomousCommand::IsFinished() {
    return false;
}

void AutonomousCommand::End() {

}

void AutonomousCommand::Interrupted() {

}
