// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
#define CheckDigitalInputChannel(n) (switchValues & (1 << n)) //where n is the channel

#include "AutonomousCommand.h"

uint8_t _3277_visionStatus, _3277_targetPosition;

AutonomousCommand::AutonomousCommand(): Command() {
	Requires(Robot::driveTrain.get());
	Requires(Robot::lifter.get());

}

void AutonomousCommand::Initialize() {
	i2cBus = new I2C(I2C::kMXP, 0x29);
}

void AutonomousCommand::Execute() {
	i2cBus->Read(0x00, 1, &_3277_visionStatus);
	if(_3277_visionStatus != 0) //Can I see anything?
	{
		switch(_3277_visionStatus)
		{
		case 0x01: //I see the goal
			i2cBus->Read(0x01, 1, &_3277_targetPosition);
			break;
		case 0x02: //I see the LowBar
			i2cBus->Read(0x02, 1, &_3277_targetPosition);
			break;
		default:
			printf("I2C error: Status is not 0, 1, or 2!");
		}
	}
	printf("VisionStatus: %d\tTarget: %d\n", _3277_visionStatus, _3277_targetPosition);

	switch(_3277_visionStatus){
	case 0: //Nothing seen
		break;
	case 1: //tower

		break;
	case 2: //lowbar
		break;
	default:
		printf("I DON'T KNOW WHAT i SEE!!!");
	}
}

bool AutonomousCommand::IsFinished() {
    return false;
}

void AutonomousCommand::End() {

}

void AutonomousCommand::Interrupted() {

}
