// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "DriveWithJoysticks.h"

DriveWithJoysticks::DriveWithJoysticks(): Command() {
	Requires(Robot::driveTrain.get());
}


void DriveWithJoysticks::Initialize() {
	Robot::driveTrain.get()->openmotors();
}

void DriveWithJoysticks::Execute() {
	Robot::driveTrain.get()->setdrive(Robot::oi.get()->getXBoxController().get()->GetY(),
			Robot::oi.get()->getXBoxController().get()->GetRawAxis(5));
}

bool DriveWithJoysticks::IsFinished() {
    return false;
}

void DriveWithJoysticks::End() {

}

void DriveWithJoysticks::Interrupted() {

}
